apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ulahcaf9f-go-gitops
  description: This is GitOps manifest for ulahcaf9f-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ulahcaf9f-go
    backstage.io/kubernetes-id: ulahcaf9f-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ulahcaf9f-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ulahcaf9f-go
